from pathlib import Path

ROOT_DIR = Path('~', 'Desktop', 'MPHYGB06_coursework_2018').expanduser()

BACKGROUND = 0
CSF = 1
GREY_MATTER = 2
WHITE_MATTER = 3
BRAIN = 4

FINAL_TEMPLATE = 'final'

BENDING_ENERGY_DEFAULT = 0.05
BETA_DEFAULT = 0.5
EPSILON_CONVERGENCE_DEFAULT = 1e-5
